classfiles = Test.class TestLex.class TestThrough.class
javafiles = Test.java TestLex.java TestThrough.java


all : $(javafiles) $(classfiles)
	


clean : 
	



.SUFFIXES: .java .class

.java.class : 
	javac $<



