/*****************************************************************
 * Source file : ../input/kernelmsg.idl
 * Platform    : V4 Generic
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.0.2 (roadrunner) on 16/06/2006 17:37
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include "kernelmsg_template_server.h"

/* Interface with_kernelmsg */

IDL4_INLINE void with_kernelmsg_pagefault_implementation(CORBA_Object _caller, const CORBA_long addr, const CORBA_long ip, const CORBA_long priv, idl4_fpage_t *fp, idl4_server_environment *_env)

{
  /* implementation of with_kernelmsg::pagefault */
  
  return;
}

IDL4_PUBLISH_WITH_KERNELMSG_PAGEFAULT(with_kernelmsg_pagefault_implementation);

IDL4_INLINE void with_kernelmsg_fake_pagefault_implementation(CORBA_Object _caller, const CORBA_long addr, const CORBA_long ip, const CORBA_long priv, idl4_fpage_t *fp, idl4_server_environment *_env)

{
  /* implementation of with_kernelmsg::fake_pagefault */
  
  return;
}

IDL4_PUBLISH_WITH_KERNELMSG_FAKE_PAGEFAULT(with_kernelmsg_fake_pagefault_implementation);

void *with_kernelmsg_vtable[WITH_KERNELMSG_DEFAULT_VTABLE_SIZE] = WITH_KERNELMSG_DEFAULT_VTABLE;
void *with_kernelmsg_ktable[WITH_KERNELMSG_DEFAULT_KTABLE_SIZE] = WITH_KERNELMSG_DEFAULT_KTABLE;

void with_kernelmsg_server(void)

{
  L4_ThreadId_t partner;
  L4_MsgTag_t msgtag;
  idl4_msgbuf_t msgbuf;
  long cnt;

  idl4_msgbuf_init(&msgbuf);
  for (cnt = 0;cnt < WITH_KERNELMSG_STRBUF_SIZE;cnt++)
    idl4_msgbuf_add_buffer(&msgbuf, malloc(8000), 8000);

  while (1)
    {
      partner = L4_nilthread;
      msgtag.raw = 0;
      cnt = 0;

      while (1)
        {
          idl4_msgbuf_sync(&msgbuf);

          idl4_reply_and_wait(&partner, &msgtag, &msgbuf, &cnt);

          if (idl4_is_error(&msgtag))
            break;

          if (IDL4_EXPECT_FALSE(idl4_is_kernel_message(msgtag)))
            idl4_process_request(&partner, &msgtag, &msgbuf, &cnt, with_kernelmsg_ktable[idl4_get_kernel_message_id(msgtag) & WITH_KERNELMSG_KID_MASK]);
            else idl4_process_request(&partner, &msgtag, &msgbuf, &cnt, with_kernelmsg_vtable[idl4_get_function_id(&msgtag) & WITH_KERNELMSG_FID_MASK]);
        }
    }
}

void with_kernelmsg_discard(void)

{
}

