

testall : test test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test17 test18 test19 test20 test21 test22 test23 test24 test25 test26 test27 test28 test29 test30 test31 test32 test33 test34 test35 test36 test37 test38 test39 test40 test41 test42 test43 test44 test45 test46 test47 test48 test49 test50 test51 test52 test53 test54 test55 test56 test57 test58 test59 test60 test61 test62 test63 test64 test65 test66 test67 test68 test69 test70 test71 test72 test73 test74 test75 test76 test77 test78 test79 test80 test81 test83 test84 test85 test86 test87
	


clean : 
	


test : test.c
	java -classpath .:..:../examples:../grammars Test test.c


test2 : test2.c
	java -classpath .:..:../examples:../grammars Test test2.c


test3 : test3.c
	java -classpath .:..:../examples:../grammars Test test3.c


test4 : test4.c
	java -classpath .:..:../examples:../grammars Test test4.c


test5 : test5.c
	java -classpath .:..:../examples:../grammars Test test5.c


test6 : test6.c
	java -classpath .:..:../examples:../grammars Test test6.c


test7 : test7.c
	java -classpath .:..:../examples:../grammars Test test7.c


test8 : test8.c
	java -classpath .:..:../examples:../grammars Test test8.c


test9 : test9.c
	java -classpath .:..:../examples:../grammars Test test9.c


test10 : test10.c
	java -classpath .:..:../examples:../grammars Test test10.c


test11 : test11.c
	java -classpath .:..:../examples:../grammars Test test11.c


test12 : test12.c
	java -classpath .:..:../examples:../grammars Test test12.c


test13 : test13.c
	java -classpath .:..:../examples:../grammars Test test13.c


test14 : test14.c
	java -classpath .:..:../examples:../grammars Test test14.c


test15 : test15.c
	java -classpath .:..:../examples:../grammars Test test15.c


test16 : test16.c
	java -classpath .:..:../examples:../grammars Test test16.c


test17 : test17.c
	java -classpath .:..:../examples:../grammars Test test17.c


test18 : test18.c
	java -classpath .:..:../examples:../grammars Test test18.c


test19 : test19.c
	java -classpath .:..:../examples:../grammars Test test19.c


test20 : test20.c
	java -classpath .:..:../examples:../grammars Test test20.c


test21 : test21.c
	java -classpath .:..:../examples:../grammars Test test21.c


test22 : test22.c
	java -classpath .:..:../examples:../grammars Test test22.c


test23 : test23.c
	java -classpath .:..:../examples:../grammars Test test23.c


test24 : test24.c
	java -classpath .:..:../examples:../grammars Test test24.c


test25 : test25.c
	java -classpath .:..:../examples:../grammars Test test25.c


test26 : test26.c
	java -classpath .:..:../examples:../grammars Test test26.c


test27 : test27.c
	java -classpath .:..:../examples:../grammars Test test27.c


test28 : test28.c
	java -classpath .:..:../examples:../grammars Test test28.c


test29 : test29.c
	java -classpath .:..:../examples:../grammars Test test29.c


test30 : test30.c
	java -classpath .:..:../examples:../grammars Test test30.c


test31 : test31.c
	java -classpath .:..:../examples:../grammars Test test31.c


test32 : test32.c
	java -classpath .:..:../examples:../grammars Test test32.c


test33 : test33.c
	java -classpath .:..:../examples:../grammars Test test33.c


test34 : test34.c
	java -classpath .:..:../examples:../grammars Test test34.c


test35 : test35.c
	java -classpath .:..:../examples:../grammars Test test35.c


test36 : test36.c
	java -classpath .:..:../examples:../grammars Test test36.c


test37 : test37.c
	java -classpath .:..:../examples:../grammars Test test37.c


test38 : test38.c
	java -classpath .:..:../examples:../grammars Test test38.c


test39 : test39.c
	java -classpath .:..:../examples:../grammars Test test39.c


test40 : test40.c
	java -classpath .:..:../examples:../grammars Test test40.c


test41 : test41.c
	java -classpath .:..:../examples:../grammars Test test41.c


test42 : test42.c
	java -classpath .:..:../examples:../grammars Test test42.c


test43 : test43.c
	java -classpath .:..:../examples:../grammars Test test43.c


test44 : test44.c
	java -classpath .:..:../examples:../grammars Test test44.c


test45 : test45.c
	java -classpath .:..:../examples:../grammars Test test45.c


test46 : test46.c
	java -classpath .:..:../examples:../grammars Test test46.c


test47 : test47.c
	java -classpath .:..:../examples:../grammars Test test47.c


test48 : test48.c
	java -classpath .:..:../examples:../grammars Test test48.c


test49 : test49.c
	java -classpath .:..:../examples:../grammars Test test49.c


test50 : test50.c
	java -classpath .:..:../examples:../grammars Test test50.c


test51 : test51.c
	java -classpath .:..:../examples:../grammars Test test51.c


test52 : test52.c
	java -classpath .:..:../examples:../grammars Test test52.c


test53 : test53.c
	java -classpath .:..:../examples:../grammars Test test53.c


test54 : test54.c
	java -classpath .:..:../examples:../grammars Test test54.c


test55 : test55.c
	java -classpath .:..:../examples:../grammars Test test55.c


test56 : test56.c
	java -classpath .:..:../examples:../grammars Test test56.c


test57 : test57.c
	java -classpath .:..:../examples:../grammars Test test57.c


test58 : test58.c
	java -classpath .:..:../examples:../grammars Test test58.c


test59 : test59.c
	java -classpath .:..:../examples:../grammars Test test59.c


test60 : test60.c
	java -classpath .:..:../examples:../grammars Test test60.c


test61 : test61.c
	java -classpath .:..:../examples:../grammars Test test61.c


test62 : test62.c
	java -classpath .:..:../examples:../grammars Test test62.c


test63 : test63.c
	java -classpath .:..:../examples:../grammars Test test63.c


test64 : test64.c
	java -classpath .:..:../examples:../grammars Test test64.c


test65 : test65.c
	java -classpath .:..:../examples:../grammars Test test65.c


test66 : test66.c
	java -classpath .:..:../examples:../grammars Test test66.c


test67 : test67.c
	java -classpath .:..:../examples:../grammars Test test67.c


test68 : test68.c
	java -classpath .:..:../examples:../grammars Test test68.c


test69 : test69.c
	java -classpath .:..:../examples:../grammars Test test69.c


test70 : test70.c
	java -classpath .:..:../examples:../grammars Test test70.c


test71 : test71.c
	java -classpath .:..:../examples:../grammars Test test71.c


test72 : test72.c
	java -classpath .:..:../examples:../grammars Test test72.c


test73 : test73.c
	java -classpath .:..:../examples:../grammars Test test73.c


test74 : test74.c
	java -classpath .:..:../examples:../grammars Test test74.c


test75 : test75.c
	java -classpath .:..:../examples:../grammars Test test75.c


test76 : test76.c
	java -classpath .:..:../examples:../grammars Test test76.c


test77 : test77.c
	java -classpath .:..:../examples:../grammars Test test77.c


test78 : test78.c
	java -classpath .:..:../examples:../grammars Test test78.c


test79 : test79.c
	java -classpath .:..:../examples:../grammars Test test79.c


test80 : test80.c
	java -classpath .:..:../examples:../grammars Test test80.c


test81 : test81.c
	java -classpath .:..:../examples:../grammars Test test81.c


test83 : test83.c
	java -classpath .:..:../examples:../grammars Test test83.c


test84 : test84.c
	java -classpath .:..:../examples:../grammars Test test84.c


test85 : test85.c
	java -classpath .:..:../examples:../grammars Test test85.c


test86 : test86.c
	java -classpath .:..:../examples:../grammars Test test86.c


test87 : test87.c
	java -classpath .:..:../examples:../grammars Test test87.c



