/* 
 * This is an automatically-generated file.
 * Source file  : {*-?generator.get_idl_filename()-*}
 * Output file  : {*-?generator.get_output_filename()-*}
 * Platform     : V4 Generic
 * Mapping      : {*-?templates.MAPPING-*}
 *
 * Generated by {*-?file.version_string-*}
*/
