There are 9 section headers, starting at offset 0x23c:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        00000000 000034 0001bc 00  AX  0   0  4
  [ 2] .rel.text         REL             00000000 000438 0000c0 08      7   1  4
  [ 3] .data             PROGBITS        00000000 0001f0 000000 00  WA  0   0  1
  [ 4] .bss              NOBITS          00000000 0001f0 000000 00  WA  0   0  1
  [ 5] .comment          PROGBITS        00000000 0001f0 000012 00      0   0  1
  [ 6] .shstrtab         STRTAB          00000000 000202 000039 00      0   0  1
  [ 7] .symtab           SYMTAB          00000000 0003a4 000080 10      8   7  4
  [ 8] .strtab           STRTAB          00000000 000424 000014 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)
