
Elf file type is EXEC (Executable file)
Entry point 0x146b60
There are 4 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x0000c0 0xf0100200 0x00100200 0x0a74a 0x0a74a RWE 0x10
  LOAD           0x00b000 0xf010c000 0x0010c000 0x0f848 0x0f848 RWE 0x800
  LOAD           0x01b000 0x0013c000 0x0013c000 0x0af9c 0x0af9c RWE 0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RWE 0x4

 Section to Segment mapping:
  Segment Sections...
   00     .text 
   01     .rodata .kip .cpulocal .data .kdebug .sets 
   02     .init 
   03     
