There are 22 section headers, starting at offset 0x108030:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        f0100200 0000c0 00a74a 00 WAX  0   0 16
  [ 2] .rodata           PROGBITS        f010c000 00b000 004b34 00   A  0   0 32
  [ 3] .kip              PROGBITS        f0111000 010000 0008a7 00 WAX  0   0 32
  [ 4] .cpulocal         PROGBITS        f0112000 011000 001920 00  WA  0   0 2048
  [ 5] .data             PROGBITS        f0114000 013000 0014bd 00  WA  0   0 32
  [ 6] .kdebug           PROGBITS        f0116000 015000 005517 00  AX  0   0 16
  [ 7] .sets             PROGBITS        f011b517 01a517 000331 00  WA  0   0  4
  [ 8] .init             PROGBITS        0013c000 01b000 00af9c 00 WAX  0   0 4096
  [ 9] .debug_abbrev     PROGBITS        00000000 025f9c 00dd4a 00      0   0  1
  [10] .debug_info       PROGBITS        00000000 033ce6 0a8ae8 00      0   0  1
  [11] .debug_line       PROGBITS        00000000 0dc7ce 00bef0 00      0   0  1
  [12] .debug_frame      PROGBITS        00000000 0e86c0 001dc4 00      0   0  4
  [13] .debug_loc        PROGBITS        00000000 0ea484 00cecb 00      0   0  1
  [14] .debug_pubnames   PROGBITS        00000000 0f734f 003305 00      0   0  1
  [15] .debug_aranges    PROGBITS        00000000 0fa654 000a58 00      0   0  1
  [16] .debug_ranges     PROGBITS        00000000 0fb0ac 002260 00      0   0  1
  [17] .debug_str        PROGBITS        00000000 0fd30c 00a4cb 01  MS  0   0  1
  [18] .comment          PROGBITS        00000000 1077d7 000785 00      0   0  1
  [19] .shstrtab         STRTAB          00000000 107f5c 0000d1 00      0   0  1
  [20] .symtab           SYMTAB          00000000 1083a0 002a10 10     21 219  4
  [21] .strtab           STRTAB          00000000 10adb0 004723 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)
