
Elf file type is EXEC (Executable file)
Entry point 0x80050030
There are 2 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x001000 0x80050000 0x00050000 0x16545 0x16545 R E 0x1000
  LOAD           0x018000 0x80067000 0x00067000 0x0ea18 0x0ea18 RWE 0x1000

 Section to Segment mapping:
  Segment Sections...
   00     .text .rodata 
   01     .kip .data .kdebug .sets .init 
