
Elf file type is EXEC (Executable file)
Entry point 0x80050020
There are 7 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x010000 0x80050000 0x00050000 0x21a88 0x21f50 RWE 0x10000
  LOAD           0x031f50 0x80071f50 0x00071f50 0x02ee0 0x02ee0 RWE 0x10000
  LOAD           0x040000 0x00100000 0x00480000 0x112a0 0x24000 RWE 0x10000
  LOAD           0x0512a0 0x00170000 0x00075000 0x02000 0x02000 RW  0
  LOAD           0x060000 0x00130000 0x004a8000 0x09100 0x09228 RWE 0x10000
  LOAD           0x070000 0x00140000 0x004b8000 0x0a130 0x0a278 RWE 0x10000
  LOAD           0x080000 0x00150000 0x004c8000 0x18140 0x1de08 RWE 0x10000

 Section to Segment mapping:
  Segment Sections...
   00     kernel.text kernel.rodata kernel.kip kernel.data kernel.kdebug kernel.sets kernel.bss 
   01     kernel.kdebug-data kernel.init 
   02     iguana_server.text iguana_server.rodata iguana_server.reginfo iguana_server.data iguana_server.sbss iguana_server.bss 
   03     bootinfo 
   04     ig_naming.text ig_naming.rodata ig_naming.reginfo ig_naming.data ig_naming.sbss ig_naming.bss 
   05     ig_serial.text ig_serial.rodata ig_serial.reginfo ig_serial.data ig_serial.sbss ig_serial.bss 
   06     test.text test.rodata test.reginfo test.data test.sbss test.bss 
