There are 11 section headers, starting at offset 0x26a60:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        80050000 001000 010068 00  AX  0   0  8
  [ 2] .rodata           PROGBITS        80061000 012000 005545 00   A  0   0  8
  [ 3] .kip              PROGBITS        80067000 018000 000898 00 WAX  0   0  8
  [ 4] .data             PROGBITS        80068000 019000 005660 00  WA  0   0 4096
  [ 5] .kdebug           PROGBITS        8006d660 01e660 005e80 00  AX  0   0  8
  [ 6] .sets             PROGBITS        800734e0 0244e0 0006b0 00  WA  0   0  8
  [ 7] .init             PROGBITS        80074000 025000 001a18 00  AX  0   0  8
  [ 8] .shstrtab         STRTAB          00000000 026a18 000048 00      0   0  1
  [ 9] .symtab           SYMTAB          00000000 026c18 003200 10     10 371  4
  [10] .strtab           STRTAB          00000000 029e18 004e87 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)
