#!/usr/bin/env python
#
# @LICENCE("Open Kernel Labs, Inc.", "2007")@
#

import sys
from traceback import print_exc

if "--traceback" in sys.argv:
    traceback = sys.argv.index("--traceback")
    del sys.argv[traceback]
else:
    traceback = 0

try:
    from adorn.main import main
    main(sys.argv)
except KeyboardInterrupt:
    pass
except SystemExit, exit_code:
    sys.exit(exit_code)
except:
    import sys
    print "Elfadorn error:", sys.exc_info()[1]
    if traceback:
        print "Now printing a traceback."
        print
        print_exc(file=sys.stdout)
        print
    sys.exit(1)
