/*****************************************************************
 * Source file : ../input/simple.idl4
 * Platform    : V4 Generic
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.0.2 (roadrunner) on 15/03/2005 13:26
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include "simple_template_server.h"

/* Interface iguana_pd */

IDL4_INLINE CORBA_long iguana_pd_create_memsection_implementation(CORBA_Object _caller, const CORBA_long inputarg, CORBA_long *result, idl4_server_environment *_env)

{
  CORBA_long __retval = 0;

  /* implementation of iguana_pd::create_memsection */
  
  return __retval;
}

IDL4_PUBLISH_IGUANA_PD_CREATE_MEMSECTION(iguana_pd_create_memsection_implementation);

void *iguana_pd_vtable[IGUANA_PD_DEFAULT_VTABLE_SIZE] = IGUANA_PD_DEFAULT_VTABLE;

void iguana_pd_server(void)

{
  L4_ThreadId_t partner;
  L4_MsgTag_t msgtag;
  idl4_msgbuf_t msgbuf;
  long cnt;

  idl4_msgbuf_init(&msgbuf);
  for (cnt = 0;cnt < IGUANA_PD_STRBUF_SIZE;cnt++)
    idl4_msgbuf_add_buffer(&msgbuf, malloc(8000), 8000);

  while (1)
    {
      partner = L4_nilthread;
      msgtag.raw = 0;
      cnt = 0;

      while (1)
        {
          idl4_msgbuf_sync(&msgbuf);

          idl4_reply_and_wait(&partner, &msgtag, &msgbuf, &cnt);

          if (idl4_is_error(&msgtag))
            break;

          idl4_process_request(&partner, &msgtag, &msgbuf, &cnt, iguana_pd_vtable[idl4_get_function_id(&msgtag) & IGUANA_PD_FID_MASK]);
        }
    }
}

void iguana_pd_discard(void)

{
}

