/* 
 * This is an automatically-generated file.
 * Source file  : {*-?generator.get_idl_filename()-*}
 * Output file  : {*-?generator.get_output_filename()-*}
 * Platform     : V4 ARM (big UUID)
 * Mapping      : {*-?templates.MAPPING-*}
 *
 * Generated by {*-?file.version_string-*}
*/

#define IDL4_OMIT_FRAME_POINTER 0 /* Unimplemented */
#define IDL4_USE_FASTCALL 0 /* Unimplemented */
#define IDL4_NEED_MALLOC 0 /* Unimplemented */
#define IDL4_API v4
#define IDL4_ARCH arm_biguuid
